// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw0vEQKN4BG1OtLE1nAuRXUvoq0r--dlo',
    appId: '1:177855430475:web:5f26e3d1791c24f7e4b2ce',
    messagingSenderId: '177855430475',
    projectId: 'e-library-cb1a6',
    authDomain: 'e-library-cb1a6.firebaseapp.com',
    storageBucket: 'e-library-cb1a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5udg4hDIBX-EMaXbCC_cmbmaUmJQ_14Q',
    appId: '1:177855430475:android:e22f0fdb6b44859fe4b2ce',
    messagingSenderId: '177855430475',
    projectId: 'e-library-cb1a6',
    storageBucket: 'e-library-cb1a6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw0vEQKN4BG1OtLE1nAuRXUvoq0r--dlo',
    appId: '1:177855430475:web:16c6eef337b9c4e4e4b2ce',
    messagingSenderId: '177855430475',
    projectId: 'e-library-cb1a6',
    authDomain: 'e-library-cb1a6.firebaseapp.com',
    storageBucket: 'e-library-cb1a6.appspot.com',
  );
}
